const authRoute = require('./auth')
const adminAuthRouter = require('./admin/auth')
const productRouter = require('./product')
const categoryRouter = require('./category')
const cartRouter = require('./cart')
const initialRouter = require('./admin/initialData')
const pageRouter = require('./admin/page')
const addressRouter = require('./address')
const orderRouter = require('./order')
const orderAdminRouter = require('./admin/orderAdmin')
const roleRouter = require('./admin/role')
const postRouter = require('./post')
const screenRouter = require('./screen')
const commentRouter = require('./comment')
const bannerRouter = require('./banner')
const actionRouter = require('./action')
const tagRouter = require('./tag')
const roleactionRouter = require('./roleaction')
const infoProductRouter = require('./infoProduct')
const paymentRouter = require('./payment')
const totalView = require('./totalView')

function route(app) {
    app.use('/admin/order', orderAdminRouter)
    app.use('/page', pageRouter)
    app.use('/buyer/cart', cartRouter)
    app.use('/buyer/order', orderRouter)
    app.use('/buyer/address', addressRouter)
    app.use('/category', categoryRouter)
    app.use('/product', productRouter)
    app.use('/admin', adminAuthRouter)
    app.use('/init', initialRouter)
    app.use('/buyer', authRoute)
    app.use('/role', roleRouter)
    app.use('/post', postRouter)
    app.use('/screen', screenRouter)
    app.use('/comment', commentRouter)
    app.use('/banner', bannerRouter)
    app.use('/action', actionRouter)
    app.use('/tag', tagRouter)
    app.use('/roleaction', roleactionRouter)
    app.use('/infoProduct', infoProductRouter)
    app.use('/api', paymentRouter)
    app.use('/totalView', totalView)
}

module.exports = route
